### ISSUE TITLE
variant classification in <app>

### ISSUE THREAD

**Issue by torstenroeder** [NesbiDevelopment/Variance-Viewer#1]
In the TEI download file, the <app> element sometimes contains the variant classification, e.g. `<app type="de.uniwue.diff.variance.CONTENT">`. I assume it was the intention to insert it always when possible, but currently it seems that is it inserted very rarely.

**Comment by NesbiDevelopment** [comment]
There should always be a type. 
I'm currently working on resolving the issue.

**Comment by NesbiDevelopment** [comment]
The type attribute was not correctly set on export to pageXML and therefore lead to missing variance types in all Changes that are not only Insert or Delete.
Since all changes, inserts and deletes are displayed as <app><lem/><rdg/><app> which made it seem random.

A fix has been applied with aa704c4c904a82e9cd2416f0e60bbfa18d33ccf8 and an update for the [webapp](http://variance-viewer.informatik.uni-wuerzburg.de/Variance-Viewer/) should follow tomorrow morning.

(This comment will be updated when the changes are online on the server)
